name: Packer-Validate

on: [pull_request]

jobs:
  packer-validate:
    runs-on: ubuntu-latest
    name: packer-validate

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@85839311bf6d0a1a8e0bd26dfac5311bc9f7d6ad
        with:
          command: validate
          arguments: "--var-file=ubunutu-vars.pkr"
          target: ubuntu.pkr.hcl
